[build]
target = "x86_64-hacal_os.json"
rustflags = [
    "-C",
    "target-feature=-sse,-sse2,-avx,-avx2"
]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
json-target-spec = true

[target.'cfg(target_os = "none")']
rustflags = ["-C", "link-arg=-Tlinker.ld"]